-- MySQL Script generated by MySQL Workbench
-- Thu Mar 26 18:57:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema audipaq
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema audipaq
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `audipaq` DEFAULT CHARACTER SET utf8mb4 ;
USE `audipaq` ;

-- -----------------------------------------------------
-- Table `audipaq`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audipaq`.`area` (
  `id_area` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_area` VARCHAR(200) NOT NULL,
  `encargado_area` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_area`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `audipaq`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audipaq`.`empresa` (
  `id_empresa` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_empresa` VARCHAR(200) NOT NULL,
  `logotipo` VARCHAR(255) NULL DEFAULT NULL,
  `giro` VARCHAR(200) NOT NULL,
  `mision` VARCHAR(200) NOT NULL,
  `vision` VARCHAR(200) NOT NULL,
  `valores` VARCHAR(200) NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `telefono` VARCHAR(200) NOT NULL,
  `correo_electronico` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `audipaq`.`tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audipaq`.`tipousuario` (
  `id_tipousuario` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_tipousuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `audipaq`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audipaq`.`persona` (
  `id_persona` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_persona` VARCHAR(200) NOT NULL,
  `apellido_paterno` VARCHAR(200) NOT NULL,
  `apellido_materno` VARCHAR(200) NOT NULL,
  `correo_electronico` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(200) NOT NULL,
  `fk_id_empresa` INT(10) UNSIGNED NOT NULL,
  `fk_id_tipo` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_persona`),
  INDEX `persona_fk_id_empresa_foreign` (`fk_id_empresa` ASC),
  INDEX `persona_fk_id_tipo_foreign` (`fk_id_tipo` ASC),
  CONSTRAINT `persona_fk_id_empresa_foreign`
    FOREIGN KEY (`fk_id_empresa`)
    REFERENCES `audipaq`.`empresa` (`id_empresa`),
  CONSTRAINT `persona_fk_id_tipo_foreign`
    FOREIGN KEY (`fk_id_tipo`)
    REFERENCES `audipaq`.`tipousuario` (`id_tipousuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `audipaq`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audipaq`.`departamento` (
  `id_departamento` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_departamento` VARCHAR(200) NOT NULL,
  `encargado_departamento` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `audipaq`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audipaq`.`status` (
  `id_status` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_status` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `audipaq`.`acta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audipaq`.`acta` (
  `id_acta` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATETIME NOT NULL,
  `fecha_final` DATETIME NOT NULL,
  `fk_id_persona` INT(10) UNSIGNED NOT NULL,
  `fk_id_auditor` INT(10) UNSIGNED NOT NULL,
  `fk_id_status` INT(10) UNSIGNED NOT NULL,
  `fk_id_area` INT(10) UNSIGNED NOT NULL,
  `fk_id_departamento` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_acta`),
  INDEX `acta_fk_id_persona_foreign` (`fk_id_persona` ASC),
  INDEX `acta_fk_id_auditor_foreign` (`fk_id_auditor` ASC),
  INDEX `acta_fk_id_status_foreign` (`fk_id_status` ASC),
  INDEX `acta_fk_id_area_foreign` (`fk_id_area` ASC),
  INDEX `acta_fk_id_departamento_foreign` (`fk_id_departamento` ASC),
  CONSTRAINT `acta_fk_id_area_foreign`
    FOREIGN KEY (`fk_id_area`)
    REFERENCES `audipaq`.`area` (`id_area`),
  CONSTRAINT `acta_fk_id_auditor_foreign`
    FOREIGN KEY (`fk_id_auditor`)
    REFERENCES `audipaq`.`persona` (`id_persona`),
  CONSTRAINT `acta_fk_id_departamento_foreign`
    FOREIGN KEY (`fk_id_departamento`)
    REFERENCES `audipaq`.`departamento` (`id_departamento`),
  CONSTRAINT `acta_fk_id_persona_foreign`
    FOREIGN KEY (`fk_id_persona`)
    REFERENCES `audipaq`.`persona` (`id_persona`),
  CONSTRAINT `acta_fk_id_status_foreign`
    FOREIGN KEY (`fk_id_status`)
    REFERENCES `audipaq`.`status` (`id_status`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `audipaq`.`doc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audipaq`.`doc` (
  `id_doc` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_doc` VARCHAR(100) NOT NULL,
  `evidencia` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_doc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `audipaq`.`prioridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audipaq`.`prioridad` (
  `id_prioridad` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_prioridad` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_prioridad`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `audipaq`.`observaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audipaq`.`observaciones` (
  `id_observaciones` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `comentarios` VARCHAR(300) NOT NULL,
  `fk_id_status` INT(10) UNSIGNED NOT NULL,
  `fk_id_auditor` INT(10) UNSIGNED NOT NULL,
  `fk_id_acta` INT(10) UNSIGNED NOT NULL,
  `fk_id_prioridad` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_observaciones`),
  INDEX `observaciones_fk_id_status_foreign` (`fk_id_status` ASC),
  INDEX `observaciones_fk_id_auditor_foreign` (`fk_id_auditor` ASC),
  INDEX `observaciones_fk_id_acta_foreign` (`fk_id_acta` ASC),
  INDEX `observaciones_fk_id_prioridad_foreign` (`fk_id_prioridad` ASC),
  CONSTRAINT `observaciones_fk_id_acta_foreign`
    FOREIGN KEY (`fk_id_acta`)
    REFERENCES `audipaq`.`acta` (`id_acta`),
  CONSTRAINT `observaciones_fk_id_auditor_foreign`
    FOREIGN KEY (`fk_id_auditor`)
    REFERENCES `audipaq`.`persona` (`id_persona`),
  CONSTRAINT `observaciones_fk_id_prioridad_foreign`
    FOREIGN KEY (`fk_id_prioridad`)
    REFERENCES `audipaq`.`prioridad` (`id_prioridad`),
  CONSTRAINT `observaciones_fk_id_status_foreign`
    FOREIGN KEY (`fk_id_status`)
    REFERENCES `audipaq`.`status` (`id_status`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `audipaq`.`detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audipaq`.`detalle` (
  `id_detalle` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `fk_id_area` INT(10) UNSIGNED NOT NULL,
  `fk_id_persona` INT(10) UNSIGNED NOT NULL,
  `fk_id_doc` INT(10) UNSIGNED NOT NULL,
  `fk_id_observaciones` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_detalle`),
  INDEX `detalle_fk_id_area_foreign` (`fk_id_area` ASC),
  INDEX `detalle_fk_id_persona_foreign` (`fk_id_persona` ASC),
  INDEX `detalle_fk_id_doc_foreign` (`fk_id_doc` ASC),
  INDEX `detalle_fk_id_observaciones_foreign` (`fk_id_observaciones` ASC),
  CONSTRAINT `detalle_fk_id_area_foreign`
    FOREIGN KEY (`fk_id_area`)
    REFERENCES `audipaq`.`area` (`id_area`),
  CONSTRAINT `detalle_fk_id_doc_foreign`
    FOREIGN KEY (`fk_id_doc`)
    REFERENCES `audipaq`.`doc` (`id_doc`),
  CONSTRAINT `detalle_fk_id_observaciones_foreign`
    FOREIGN KEY (`fk_id_observaciones`)
    REFERENCES `audipaq`.`observaciones` (`id_observaciones`),
  CONSTRAINT `detalle_fk_id_persona_foreign`
    FOREIGN KEY (`fk_id_persona`)
    REFERENCES `audipaq`.`persona` (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `audipaq`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audipaq`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
